### ISSUE TITLE
Deprecated retro_ditherize.py is causing import errors

### ISSUE THREAD

**Issue by zealsprince** [Ar7ific1al/invokeai-retroizeinode#3]
Hey there!

I've noticed that you updated all your invocations to the newest version of InvokeAI and deprecated the [retro_ditherize.py](https://github.com/Ar7ific1al/invokeai-retroizeinode/blob/main/retro_ditherize.py) node. However it still remains in the repository meaning that when cloning and copying the files in directly it will cause import errors. I began fixing it only to see that it was deprecated on purpose so I think the best course of action would be to remove the file entirely to avoid further errors and confusion!

**Comment by Ar7ific1al** [comment]
Oops, sorry about that! I've removed it from the repo. Thanks for pointing it out!
